Update README.md
apple/axlearn pull request #145
Opened 2023-10-25 20:27 UTC by CrypticRevenger

2023-10-28 18:18 UTC, markblee reviewed
The bullet point layout is quite neat. I'm not sure if we need to repeat the different sections from the ToC though. @ruomingp WDYT?

2023-10-28 18:30 UTC, ruomingp requested changes
I suppose this change is motivated by the formatting changes? If so, let's decouple the wording and formatting changes?

2023-10-28 18:30 UTC, ruomingp commented on README.md
> +Welcome to AXLearn, a powerful deep learning library built on top of JAX and XLA. AXLearn is designed to support the development of large-scale deep learning models and offers a unique approach to ta
The claim about "unique" is not entirely accurate. The object-oriented approach was adopted at least by lingvo and paxml.

2023-10-28 18:30 UTC, ruomingp commented on README.md
> +Welcome to AXLearn, a powerful deep learning library built on top of JAX and XLA. AXLearn is designed to support the development of large-scale deep learning models and offers a unique approach to ta
Maybe it's just me, but I'm not entirely comfortable with subjective adjectives such as "powerful". I feel that it's better for users to judge than for us to claim. WDYT?

2025-07-26 00:33 UTC, changlan commented
Closing this PR due to inactivity. Feel free to reopen if you would like to continue the work.

2025-07-26 00:33 UTC, closed without merging