refactor rnn api
apple/axlearn pull request #425
Opened 2024-04-27 00:54 UTC by zhiyun

2024-04-27 18:27 UTC, ruomingp reviewed
Thanks, Zhiyun!

2024-04-27 18:27 UTC, ruomingp commented on axlearn/audio/asr_decoder.py
>                  [batch_size, output_dim].
```suggestion
            (updated_cache_states, outputs), where `outputs` is a Tensor of shape
                [batch_size, output_dim].
```

2024-04-27 18:27 UTC, ruomingp commented on axlearn/common/rnn.py
> +             `outputs` is a Tensor of shape [batch_size, output_dim].
```suggestion
            (updated_cache_states, outputs), where:
            `updated_cache_states` is a list of states from all layers;
             `outputs` is a Tensor of shape [batch_size, output_dim].
```

2024-04-27 18:27 UTC, ruomingp commented on axlearn/common/rnn.py
>              (updated_step_states, outputs), where `outputs` are usually a Tensor of shape
Ditto.

2024-04-28 04:44 UTC, zhiyun commented on axlearn/audio/asr_decoder.py
>                  [batch_size, output_dim].
Done.

2024-04-28 04:44 UTC, zhiyun commented on axlearn/common/rnn.py
> +             `outputs` is a Tensor of shape [batch_size, output_dim].
Done.

2024-04-28 04:47 UTC, zhiyun commented on axlearn/common/rnn.py
>              (updated_step_states, outputs), where `outputs` are usually a Tensor of shape
Done.

2024-04-28 11:36 UTC, ruomingp requested changes
Please see the internal PR discussion.

2024-05-02 14:56 UTC, ruomingp approved these changes

2024-05-02 15:21 UTC, merged