Support orbax state builder
apple/axlearn pull request #866
Opened 2024-12-02 22:46 UTC by hanzhi713

This PR adds `OrbaxStateBuilder` and refactors `TensorStoreStateBuilder`, and prepares for Orbax emergency checkpointing, which cannot be meaningfully represented as a path. Therefore, we add support of using `base_dir` and `step` as arguments to Builder, which abstracts away the underlying checkpoint structure. This paves the way of letting users restore state from the results of emergency checkpoint.

This PR also upgrades orbax slightly so it supports concurrent save and restore gb.

2024-12-03 20:57 UTC, ruomingp requested changes

2024-12-03 20:57 UTC, ruomingp commented on axlearn/common/state_builder.py
> +            step: Step number to load.
Please see my question about step=None in the internal PR.

2024-12-03 21:46 UTC, ruomingp approved these changes

2024-12-05 04:14 UTC, markblee approved these changes

2024-12-06 06:02 UTC, merged