MaskFnAttentionBias._bool_value passes the same rank position tensors to mask_fn.
apple/axlearn pull request #888
Opened 2024-12-12 00:39 UTC by ds-hwang

MaskFnAttentionBias._bool_value passes the same rank position tensors to mask_fn.

When target_positions is set, a rank 3 target_positions and a rank 2
source_positions are passed to mask_fn. From the perspective of a downstream
defining mask_fn, this is a big surprise.

2024-12-12 00:41 UTC, ds-hwang commented
From 950

2024-12-12 17:52 UTC, apghml requested changes
This PR is under discussion internally.

2024-12-17 19:44 UTC, apghml approved these changes
Thanks!

2024-12-17 19:48 UTC, ruomingp approved these changes

2024-12-17 20:54 UTC, ds-hwang commented
Thank you for review!

2024-12-17 21:55 UTC, merged